accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

blog/urls.py
from django.urls import path
from .views import (
    search,
    IndexView,
    PostListView,
    PostDetailView,
)
from marketing.views import email_list_signup

app_name = 'blog'

urlpatterns = [
    path('post/list/', PostListView.as_view(), name='post-list'),
    path('search/', search, name='search'),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),

    
]

furniture/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace='account')),
    path('', include('products.urls',namespace='core')),
    path('blog/', include('blog.urls',namespace='blog')),
    path('tinymce/', include('tinymce.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Activation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE ,blank=True)
    created_at = models.DateTimeField(auto_now_add=True,blank=True)
    code = models.CharField(max_length=20, unique=True, blank=True)
    email = models.EmailField(blank=True)

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
    PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
)
from django.shortcuts import get_object_or_404, redirect
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView
from django.conf import settings

from .utils import (
    send_activation_email, send_reset_password_email, send_forgotten_username_email, send_activation_change_email,
)
from .forms import (
    SignInViaUsernameForm, SignInViaEmailForm, SignInViaEmailOrUsernameForm, SignUpForm,
    RestorePasswordForm, RestorePasswordViaEmailOrUsernameForm, RemindUsernameForm,
    ResendActivationCodeForm, ResendActivationCodeViaEmailForm, ChangeProfileForm, ChangeEmailForm,
)
from .models import Activation


class GuestOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        # Redirect to the index page if the user already authenticated
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().dispatch(request, *args, **kwargs)


class LogInView(GuestOnlyView, FormView):
    template_name = 'accounts/log_in.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME or settings.LOGIN_VIA_EMAIL:
            return SignInViaEmailForm

        if settings.LOGIN_VIA_EMAIL_OR_USERNAME:
            return SignInViaEmailOrUsernameForm

        return SignInViaUsernameForm

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        request = self.request

        # If the test cookie worked, go ahead and delete it since its no longer needed
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()

        # The default Django's "remember me" lifetime is 2 weeks and can be changed by modifying
        # the SESSION_COOKIE_AGE settings' option.
        if settings.USE_REMEMBER_ME:
            if not form.cleaned_data['remember_me']:
                request.session.set_expiry(0)

        login(request, form.user_cache)

        redirect_to = request.POST.get(REDIRECT_FIELD_NAME, request.GET.get(REDIRECT_FIELD_NAME))
        url_is_safe = is_safe_url(redirect_to, allowed_hosts=request.get_host(), require_https=request.is_secure())

        if url_is_safe:
            return redirect(redirect_to)

        return redirect(settings.LOGIN_REDIRECT_URL)


class SignUpView(GuestOnlyView, FormView):
    template_name = 'accounts/sign_up.html'
    form_class = SignUpForm

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)

        if settings.DISABLE_USERNAME:
            # Set a temporary username
            user.username = get_random_string()
        else:
            user.username = form.cleaned_data['username']

        if settings.ENABLE_USER_ACTIVATION:
            user.is_active = False

        # Create a user record
        user.save()

        # Change the username to the "user_ID" form
        if settings.DISABLE_USERNAME:
            user.username = f'user_{user.id}'
            user.save()

        if settings.ENABLE_USER_ACTIVATION:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.save()

            send_activation_email(request, user.email, code)

            messages.success(
                request, _('برای فعال کردن حساب ایمیل خود راچک کنید .'))
        else:
            raw_password = form.cleaned_data['password1']

            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            messages.success(request, _('شما با موفقیت ثبت نام کرده اید!'))

        return redirect('/')


class ActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Activate profile
        user = act.user
        user.is_active = True
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('شما با موفقیت حساب خود را فعال کرده اید!'))

        return redirect('accounts:log_in')


class ResendActivationCodeView(GuestOnlyView, FormView):
    template_name = 'accounts/resend_activation_code.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME:
            return ResendActivationCodeViaEmailForm

        return ResendActivationCodeForm

    def form_valid(self, form):
        user = form.user_cache

        activation = user.activation_set.first()
        activation.delete()

        code = get_random_string(20)

        act = Activation()
        act.code = code
        act.user = user
        act.save()

        send_activation_email(self.request, user.email, code)

        messages.success(self.request, _('کد فعال سازی جدید به آدرس ایمیل شما ارسال شده است.'))

        return redirect('accounts:resend_activation_code')


class RestorePasswordView(GuestOnlyView, FormView):
    template_name = 'accounts/restore_password.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.RESTORE_PASSWORD_VIA_EMAIL_OR_USERNAME:
            return RestorePasswordViaEmailOrUsernameForm

        return RestorePasswordForm

    def form_valid(self, form):
        user = form.user_cache
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk)).decode()

        send_reset_password_email(self.request, user.email, token, uid)

        return redirect('accounts:restore_password_done')


class ChangeProfileView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_profile.html'
    form_class = ChangeProfileForm

    def get_initial(self):
        user = self.request.user
        initial = super().get_initial()
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        return initial

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()

        messages.success(self.request, _('Profile data has been successfully updated.'))

        return redirect('accounts:change_profile')


class ChangeEmailView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_email.html'
    form_class = ChangeEmailForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        user = self.request.user
        email = form.cleaned_data['email']

        if settings.ENABLE_ACTIVATION_AFTER_EMAIL_CHANGE:
            code = get_random_string(20)

            act = Activation()
            act.code = code
            act.user = user
            act.email = email
            act.save()

            send_activation_change_email(self.request, email, code)

            messages.success(self.request, _('To complete the change of email address, click on the link sent to it.'))
        else:
            user.email = email
            user.save()

            messages.success(self.request, _('Email successfully changed.'))

        return redirect('accounts:change_email')


class ChangeEmailActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Change the email
        user = act.user
        user.email = act.email
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully changed your email!'))

        return redirect('accounts:change_email')


class RemindUsernameView(GuestOnlyView, FormView):
    template_name = 'accounts/remind_username.html'
    form_class = RemindUsernameForm

    def form_valid(self, form):
        user = form.user_cache
        send_forgotten_username_email(user.email, user.username)

        messages.success(self.request, _('Your username has been successfully sent to your email.'))

        return redirect('accounts:remind_username')


class ChangePasswordView(BasePasswordChangeView):
    template_name = 'accounts/profile/change_password.html'

    def form_valid(self, form):
        # Change the password
        user = form.save()

        # Re-authentication
        login(self.request, user)

        messages.success(self.request, _('Your password was changed.'))

        return redirect('accounts:change_password')


class RestorePasswordConfirmView(BasePasswordResetConfirmView):
    template_name = 'accounts/restore_password_confirm.html'

    def form_valid(self, form):

accounts/templates/accounts/log_in.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<!-- login
============================================= -->
<section id="register-login" class="register-login pt-30 pb-150">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-5 form-accounts">
                <div class="register-title">
                    <h4>{% trans 'ورود به حساب کاربری' %}</h4>
                   
                </div> 
                <!-- .register-title end -->
                <form class="login" method="POST" action="{% url 'accounts:log_in' %}">
                  {% csrf_token %}
                  
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-12">
                            <div class="form-group">
                                <input type="text" class="form-control" id="email" name="email" placeholder="ایمیل" required>
                            </div>
                        </div>
                        <!-- .col-lg-12 end -->
                        <div class="col-sm-12 col-md-12 col-lg-12">
                            <div class="form-group">
                                <input type="password" class="form-control" name="password" placeholder="پسورد" required>
                            </div>
                        </div>
                        <!-- .col-lg-12 end -->
                        <div class="col-sm-12 col-md-12 col-lg-12 mb-40">
                            <div class="input-checkbox inline-block">
                                <label class="label-checkbox">
                                    <input type="checkbox" checked>مرا به خاطر بسپار
                                    <span class="check-indicator"></span>
                                </label>
                            </div>
                            <a href="{% url 'accounts:restore_password' %}" class="forget--password"> فراموشی رمز عبور ؟ </a>
                        </div>
                        <!-- .col-lg-12 end -->
                        <div class="col-sm-12 col-md-12 col-lg-12 mb-30">
                            <button type="submit" class="btn btn--primary btn--rounded">ورود</button>
                           
                        </div>
                        <!-- .col-lg-12 end -->
                        <div class="col-sm-12 col-md-12 col-lg-12 mb-50">
                            <div class="social--login">
                                <span class="title">ورود با</span>
                                <a href="#" ><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="40px" height="40px"><linearGradient id="ikFC25QA3Mb2fWnkGP9OWa" x1="32" x2="32" y1="13.75" y2="55.668" gradientUnits="userSpaceOnUse" spreadMethod="reflect"><stop offset="0" stop-color="#6dc7ff"/><stop offset="1" stop-color="#e6abff"/></linearGradient><path fill="url(#ikFC25QA3Mb2fWnkGP9OWa)" d="M22.89,55.28c-0.22-1.98-0.42-5.01,0.09-7.17c0.45-1.95,2.93-12.43,2.93-12.43 s-0.75-1.5-0.75-3.71c0-3.48,2.01-6.07,4.52-6.07c2.14,0,3.17,1.6,3.17,3.52c0,2.15-1.37,5.35-2.07,8.32 c-0.59,2.49,1.24,4.52,3.7,4.52c4.44,0,7.86-4.68,7.86-11.45c0-5.98-4.3-10.17-10.45-10.17c-7.11,0-11.28,5.34-11.28,10.85 c0,2.15,0.82,4.45,1.86,5.71c0.2,0.24,0.23,0.46,0.17,0.71c-0.19,0.79-0.61,2.49-0.69,2.84c-0.11,0.46-0.37,0.55-0.84,0.33 c-3.12-1.45-5.08-6.01-5.08-9.68c0-7.89,5.73-15.13,16.52-15.13c8.68,0,15.42,6.18,15.42,14.44c0,8.61-5.44,15.55-12.98,15.55 c-2.53,0-4.91-1.32-5.73-2.87c0,0-1.25,4.77-1.55,5.94c-0.57,2.17-2.09,4.89-3.11,6.56"/><linearGradient id="ikFC25QA3Mb2fWnkGP9OWb" x1="32" x2="32" y1="3.25" y2="60.02" gradientUnits="userSpaceOnUse" spreadMethod="reflect"><stop offset="0" stop-color="#1a6dff"/><stop offset="1" stop-color="#c822ff"/></linearGradient><path fill="url(#ikFC25QA3Mb2fWnkGP9OWb)" d="M32,58C17.664,58,6,46.337,6,32S17.664,6,32,6s26,11.663,26,26S46.336,58,32,58z M32,8 C18.767,8,8,18.767,8,32s10.767,24,24,24s24-10.767,24-24S45.233,8,32,8z"/></svg></a>
                                <a href="#" ><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="40px" height="40px"><linearGradient id="7sJyQCZzdsESd~lp6E9tqa" x1="32" x2="32" y1="16.25" y2="48.312" gradientUnits="userSpaceOnUse" spreadMethod="reflect"><stop offset="0" stop-color="#6dc7ff"/><stop offset="1" stop-color="#e6abff"/></linearGradient><path fill="url(#7sJyQCZzdsESd~lp6E9tqa)" d="M26.064,45.003c12.076,0,18.68-10.005,18.68-18.68c0-0.284-0.006-0.567-0.019-0.849 c1.282-0.927,2.396-2.083,3.275-3.399c-1.176,0.523-2.442,0.875-3.77,1.034c1.355-0.813,2.396-2.099,2.887-3.632 c-1.269,0.752-2.673,1.299-4.169,1.594c-1.198-1.276-2.904-2.074-4.792-2.074c-3.626,0-6.566,2.94-6.566,6.565 c0,0.515,0.058,1.016,0.17,1.497c-5.456-0.274-10.295-2.887-13.532-6.859c-0.564,0.97-0.889,2.097-0.889,3.3 c0,2.278,1.159,4.289,2.922,5.465c-1.077-0.033-2.089-0.329-2.974-0.821c-0.001,0.027-0.001,0.055-0.001,0.084 c0,3.18,2.263,5.834,5.267,6.436c-0.551,0.15-1.132,0.231-1.731,0.231c-0.423,0-0.834-0.042-1.234-0.118 c0.836,2.608,3.259,4.506,6.133,4.56c-2.247,1.761-5.078,2.81-8.154,2.81c-0.53,0-1.052-0.03-1.566-0.091 C18.906,43.916,22.356,45.003,26.064,45.003"/><linearGradient id="7sJyQCZzdsESd~lp6E9tqb" x1="32" x2="32" y1="5.25" y2="59.38" gradientUnits="userSpaceOnUse" spreadMethod="reflect"><stop offset="0" stop-color="#1a6dff"/><stop offset="1" stop-color="#c822ff"/></linearGradient><path fill="url(#7sJyQCZzdsESd~lp6E9tqb)" d="M32,58C17.663,58,6,46.337,6,32S17.663,6,32,6s26,11.663,26,26S46.337,58,32,58z M32,8 C18.767,8,8,18.767,8,32s10.767,24,24,24s24-10.767,24-24S45.233,8,32,8z"/></svg></a>
                                <a href="#" ><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="40px" height="40px"><linearGradient id="VtgpHyLpOmfDwWf024j9Pa" x1="26.023" x2="26.023" y1="19.667" y2="43.002" gradientUnits="userSpaceOnUse" spreadMethod="reflect"><stop offset="0" stop-color="#6dc7ff"/><stop offset="1" stop-color="#e6abff"/></linearGradient><path fill="url(#VtgpHyLpOmfDwWf024j9Pa)" fill-rule="evenodd" d="M35.925,30c0.68,5-1.371,12.17-9.761,12.17 C20.55,42.17,16,37.616,16,32.003c0-5.613,4.55-10.165,10.164-10.165c2.634,0,5.034,1.001,6.839,2.645 c-2.127,2.009-2.057,2.127-2.893,2.963c-1.044-0.864-2.183-1.484-3.946-1.484c-3.335,0-5.937,2.703-5.937,6.038 c0,3.335,2.603,6.038,5.937,6.038c3.295,0,4.552-1.421,5.413-4.03c-1.59,0-5.576,0.005-5.576,0.005V30C26,30,33.938,30,35.925,30z" clip-rule="evenodd"/><linearGradient id="VtgpHyLpOmfDwWf024j9Pb" x1="32" x2="32" y1="4.667" y2="59.169" gradientUnits="userSpaceOnUse" spreadMethod="reflect"><stop offset="0" stop-color="#1a6dff"/><stop offset="1" stop-color="#c822ff"/></linearGradient><path fill="url(#VtgpHyLpOmfDwWf024j9Pb)" d="M32,58C17.663,58,6,46.337,6,32S17.663,6,32,6s26,11.663,26,26S46.337,58,32,58z M32,8 C18.767,8,8,18.767,8,32s10.767,24,24,24s24-10.767,24-24S45.233,8,32,8z"/><linearGradient id="VtgpHyLpOmfDwWf024j9Pc" x1="43.5" x2="43.5" y1="25.333" y2="37.375" gradientUnits="userSpaceOnUse" spreadMethod="reflect"><stop offset="0" stop-color="#6dc7ff"/><stop offset="1" stop-color="#e6abff"/></linearGradient><path fill="url(#VtgpHyLpOmfDwWf024j9Pc)" fill-rule="evenodd" d="M48 30L45 30 45 27 42 27 42 30 39 30 39 33 42 33 42 36 45 36 45 33 48 33z" clip-rule="evenodd"/></svg></a>
                                <a href="#" ><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="40px" height="40px"><linearGradient id="jm_nAfYbxsVmTlYr5N4x9a" x1="32" x2="32" y1="6.667" y2="57.872" gradientUnits="userSpaceOnUse" spreadMethod="reflect"><stop offset="0" stop-color="#1a6dff"/><stop offset="1" stop-color="#c822ff"/></linearGradient><path fill="url(#jm_nAfYbxsVmTlYr5N4x9a)" d="M44,57H20c-7.168,0-13-5.832-13-13V20c0-7.168,5.832-13,13-13h24c7.168,0,13,5.832,13,13v24 C57,51.168,51.168,57,44,57z M20,9C13.935,9,9,13.935,9,20v24c0,6.065,4.935,11,11,11h24c6.065,0,11-4.935,11-11V20 c0-6.065-4.935-11-11-11H20z"/><linearGradient id="jm_nAfYbxsVmTlYr5N4x9b" x1="32" x2="32" y1="18.167" y2="45.679" gradientUnits="userSpaceOnUse" spreadMethod="reflect"><stop offset="0" stop-color="#6dc7ff"/><stop offset="1" stop-color="#e6abff"/></linearGradient><path fill="url(#jm_nAfYbxsVmTlYr5N4x9b)" d="M32,45c-7.168,0-13-5.832-13-13c0-7.168,5.832-13,13-13c7.168,0,13,5.832,13,13 C45,39.168,39.168,45,32,45z M32,23c-4.962,0-9,4.038-9,9c0,4.963,4.038,9,9,9c4.963,0,9-4.037,9-9C41,27.038,36.963,23,32,23z"/><linearGradient id="jm_nAfYbxsVmTlYr5N4x9c" x1="46" x2="46" y1="12.75" y2="23.049" gradientUnits="userSpaceOnUse" spreadMethod="reflect"><stop offset="0" stop-color="#6dc7ff"/><stop offset="1" stop-color="#e6abff"/></linearGradient><path fill="url(#jm_nAfYbxsVmTlYr5N4x9c)" d="M46 15A3 3 0 1 0 46 21A3 3 0 1 0 46 15Z"/></svg></a>
                            </div>
                        </div>
                        <!-- .col-lg-12 end -->
                        <a href="{% url 'accounts:sign_up' %}" class="register-login-q"> حساب کاربری ندارید ؟ ثبت نام </a>
                    </div>
                    <!-- .row end -->
                </form>
            </div>
        </div>
        <!-- .row end -->
    </div>
    <!-- .container end -->
  </section>
  <!-- #checkout end -->
{% endblock %}

accounts/templates/accounts/log_out.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}

<section id="register-login" class="register-login pt-30 pb-150">
    <div class="container">
        <div class="row">
<div class="col-sm-12 col-md-6 col-lg-6 offset-lg-1 form-accounts">
    <div class="register-title">
        <h4>{% trans 'خروج از حساب کاربری' %}</h4>
    </div>
  
    <p>
        {% trans 'متشکرم که امروز کمی وقت با سایت سپری کردید.' %}
    </p>
    <div class="col-sm-12 col-md-12 col-lg-12 mb-40">
        <a href="{% url 'accounts:log_in' %}"><button class="btn btn--primary btn--rounded">{% trans 'ورود به حساب کاربری ' %}</button></a>
    </div>
  </div>
  <!-- .col-lg-6 end -->
</div>
<!-- .row end -->
</div>
<!-- .container end -->
</section>
<!-- #checkout end -->




{% endblock %}

accounts/templates/accounts/remind_username.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'Remind a username' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'Next' %}</button>

    </form>

    <hr>

    <ul>
        <li>
            <a href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
        </li>
    </ul>

{% endblock %}

accounts/templates/accounts/resend_activation_code.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

    <h4>{% trans 'ارسال کد فعال سازی' %}</h4>

    <form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <button class="btn btn-primary">{% trans 'بعدی' %}</button>

    </form>

    <hr>

    <ul>
        <li>
            <a href="{% url 'accounts:log_in' %}">{% trans 'ورود' %}</a>
        </li>
    </ul>

{% endblock %}