accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

blog/urls.py
from django.urls import path
from .views import (
    search,
    IndexView,
    PostListView,
    PostDetailView,
)
from marketing.views import email_list_signup

app_name = 'blog'

urlpatterns = [
    path('post/list/', PostListView.as_view(), name='post-list'),
    path('search/', search, name='search'),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    path('post/<pk>/', PostDetailView.as_view(), name='post-detail'),

    
]

furniture/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace='account')),
    path('', include('products.urls',namespace='core')),
    path('blog/', include('blog.urls',namespace='blog')),
    path('tinymce/', include('tinymce.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    AddCouponView,
    RequestRefundView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug:slug>/', ItemDetailView.as_view(), name='product-detail'),
    path('add-to-cart/<slug:slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug:slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug:slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html dir="rtl" lang="en">
<head>
    <!-- Document Meta
    ============================================= -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--IE Compatibility Meta-->
    <meta name="author" content="biotak">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="furniture">
    <link href="{% static 'assets\images\favicon\favicon.png' %}" rel="icon">


    <!-- Fonts
    ============================================= -->
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css"> 
    <!-- Stylesheets
    ============================================= -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">
    <link href="{% static 'assets\css\external.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets\css\style.css' %}">


    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->

    <!-- Document Title
    ============================================= -->
    {% block title %}
    <title>مبلمان محمودی</title>
    {% endblock title %}

</head>


<body>
    <div class="preloader">
        <div class="loader-eclipse">
            <div class="loader-content"></div>
        </div>
    </div>
    <!-- Document Wrapper
	============================================= -->
    <div id="wrapperParallax" class="wrapper clearfix">


        {% include 'header.html' %}

        {% include 'messages.html' %}

        {% block content %}

        {% endblock content %}

        {% include 'footer.html' %}

        
    </div><!-- #wrapper end -->
      
    <!-- Footer Scripts
============================================= -->

    <script src="{% static 'assets\js\jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets\js\plugins.js' %}"></script>
    <script src="{% static 'assets\js\functions.js' %}"></script>

</body>

</html>

templates/checkout.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}
<!-- checkout
============================================= -->
<section id="checkout" class="shop shop-cart checkout pt-30">
  <div class="container">
      <div class="row">
          <div class="col-sm-12 col-md-6 col-lg-6">
              <div class="cart-shiping">
                  <div class="cart--shiping-text">
                      <h3>جزییات سفارش</h3>
                  </div>
                  <form method="POST">
                    {% csrf_token %}
                      <div class="row">
                          <!-- .col-lg-12 end -->
                          <div class="col-sm-12 col-md-6 col-lg-6">
                              <div class="form-group">
                                  <label for="frist_name">نام </label>
                                  <input type="text" class="form-control" id="frist_name" name="frist_name">
                              </div>
                          </div>
                          <!-- .col-lg-6 end -->
                          <div class="col-sm-12 col-md-6 col-lg-6">
                              <div class="form-group">
                                  <label for="last_name">نام خانوادگی</label>
                                  <input type="text" class="form-control" id="last_name" name="last_name">
                              </div>
                          </div>
                          <!-- .col-lg-6 end -->
                          <div class="col-sm-12 col-md-12 col-lg-12">
                              <div class="form-group">
                                  <label for="street_address">آدرس 1</label>
                                  <input type="text" class="form-control" id="street_address" name="street_address">
                              </div>
                          </div>
                          <!-- .col-lg-12 end -->
                          <div class="col-sm-12 col-md-12 col-lg-12">
                              <div class="form-group">
                                  <label for="apartment_address">آدرس 2 (اختیاری)</label>
                                  <input type="text" class="form-control" id="apartment_address" name="apartment_address">
                              </div>
                          </div>
                          <!-- .col-lg-12 end -->
                          <div class="col-sm-12 col-md-12 col-lg-12">
                              <div class="form-group">
                                  <label for="city">شهر</label>
                                  <input type="text" class="form-control" id="city" name="city"> 
                              </div>
                          </div>
                          <!-- .col-lg-6 end -->
                          <div class="col-sm-12 col-md-6 col-lg-6">
                              <div class="form-group">
                                  <label for="zip">کدپستی</label>
                                  <input type="text" class="form-control" id="zip" name="zip">
                              </div>
                          </div>
                          <!-- .col-lg-6 end -->
                          <div class="col-sm-12 col-md-6 col-lg-6">
                              <div class="form-group">
                                  <label for="phone">شماره موبایل</label>
                                  <input type="text" class="form-control" id="phone" name="phone">
                              </div>
                          </div>
                          <!-- .col-lg-12 end -->
                          <div class="col-sm-12 col-md-12 col-lg-12">
                              <div class="form-group">
                                  <label for="note">نکات سفارش (اختیاری) </label>
                                  <textarea id="note" name="note" class="form-control"></textarea>
                              </div>
                          </div>
                          <!-- .col-lg-12 end -->
                      </div><!-- .row end -->

              </div>
              <!-- .cart-shiping end -->
          </div>
          <!-- .col-lg-6 end -->
          <div class="col-sm-12 col-md-6 col-lg-5 offset-lg-1">
              <div class="cart-total-amount">
                  <h4>سفارش شما</h4>
                  <div class="cart--products">
                      <h6>محصولات</h6>
                      <div class="clearfix"></div>
                      {% for order_item in order.items.all %}
                      <ul class="list-unstyled">
                          <li>{{ order_item.quantity }} عدد سفارش {{ order_item.item.title}}
                              <span class="price">{{ order_item.get_final_price|intcomma:False }} تومان</span>
                            </li>
                      </ul>
                      {% endfor %}
                  </div>
                  <div class="cart--total">
                      <div class="clearfix">
                          <h6>قیمت کل :  </h6>
                          <span class="price--total">{{ order.get_total|intcomma:False }} تومان </span>
                      </div>
                      <fieldset class="mb-30">
                        {% for value, name in form.fields.payment_option.choices %}
                          <div class="input-radio">
                              <label class="label-radio"  for="{{ name }}">{{ name }}
                                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" required>
                                  <span class="radio-indicator" ></span>
                              </label>
                          </div><!-- .input-radio end -->
                          {% endfor %}
                      </fieldset>
                      <button type="submit" class="btn btn--primary btn--rounded btn--block">ثبت سفارش</button>
              </div>
              <!-- .cart-total-amount end -->
          </div>
          <!-- .col-lg-5 end -->
        </form>
      </div>
      <!-- .row end -->
  </div>
  <!-- .container end -->
</section>
<!-- #checkout end -->


{% endblock content %}

templates/header.html
{% load static %}
{% load humanize %}

{% load cart_template_tags %}
<header id="navbar-spy" class="header  header-transparent">
    <nav id="primary-menu" class="navbar navbar-expand-lg navbar-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
            aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="nav-header">
            <a class="navbar-brand" href="#">
                <img class="logo " src="{% static 'assets/images/logo/logo.png' %}" alt="logo">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav">
                <!-- home Menu -->
                <li class="has-dropdown mega-dropdown active">
                    <a href="{% url 'core:home' %}" class="dropdown-toggle menu-item">صفحه اصلی</a>
                </li><!-- li end -->

                <!-- shop Menu -->
                <li class="has-dropdown">
                    <a href="#"  class="dropdown-toggle link-hover" data-hover="shop">فروشگاه</a>
                </li><!-- li end -->

                <!-- Pages Menu -->
                <li class="has-dropdown">
                    <a href="{% url 'blog:post-list' %}" class="dropdown-toggle link-hover" data-hover="pages">بیومگ</a>
                </li><!-- li end -->

                <!-- collection Menu -->
                <li class="has-dropdown mega-dropdown">
                    <a href="#"  class="dropdown-toggle menu-item">کلکسیون</a>
                </li><!-- li end -->

                <!-- Blog Menu-->
                <li class="has-dropdown">
                    <a href="#" class="dropdown-toggle menu-item">درباره ما</a>
                </li><!-- li end -->
            </ul>

        </div>
        <!-- /.navbar-collapse -->

        <!-- /.container -->
    </nav>
    <div class="module-container">
        <div class="module module-lang">
            <div class="module-icon">
                <a href="{% url 'accounts:log_in' %}"><i class="lnr lnr-user"></i></a>
            </div>

        </div>
        <!-- Module Cart -->
        <div class="module module-cart pull-left">
            <div class="module-icon cart-icon">
                <a href="{% url 'core:order-summary' %}"><i class="icon-bag"></i></a>
                <label class="module-label">{{ request.user|cart_item_count }}</label>
            </div>
        </div>
        <!-- .module-cart end -->
        <!-- Module Search -->
        <div class="module module-search pull-left">
            <div class="module-icon-search">
                <a data-toggle="modal" data-target="#search-popup"><i class="lnr lnr-magnifier"></i></a>
            </div>
        </div><!-- .module-search end -->
    </div>
</header>


<div class="modal fade search-popup modal-fullscreen" id="search-popup" tabindex="-1" role="dialog">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
            aria-hidden="true">&times;</span></button>
    <div class="pos-vertical-center">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="heading mb-90">
                        <h2 class="heading--title">جستجو</h2>
                    </div>
                    <form class="form-inline form-search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="دنبال چی می گردی ؟">
                            <button type="button"><i class="lnr lnr-arrow-left"></i></button>
                        </div>
                    </form>
                    <!-- .form-search end -->
                    <h3>
                        کلید واژه ها: صندلی ، میز ، مبل ، لاوسیت</h3>
                </div>
            </div>
        </div>
        <!-- .modal-content end -->
    </div>
</div>

templates/messages.html
{% if messages %}
{% for message in messages %}
{% if message.tags == 'success'%}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% elif message.tags == 'info'%}
<div class="alert alert-info alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% elif message.tags == 'warning'%}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% elif message.tags == 'error'%}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}
{% endfor %}
{% endif %}


{% if form.errors %}
    
    {% for error,message in form.errors.items %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
        
    
{% endif %}
    

<script>
    window.setTimeout(function () {
        $(".alert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    },5000);
</script>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block content %}
<!-- Shop Cart
============================================= -->
<section class="shop shop-cart">
    <div id="shopcart" class="container">
        <div class="row">
            <div class="col-lg">
                <div class="cart-table">
                    <table class="table">
                        <thead>
                            <tr class="cart-product">
                                <th class="cart-product-item">محصول</th>
                                <th class="cart-product-price">قیمت</th>
                                <th class="cart-product-quantity">تعداد</th>
                                <th class="cart-product-total">مجموع</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order_item in order.items.all %}
                            <!-- cart product #1 -->
                            <tr class="cart-product">
                                <td class="cart-product-item">
                                    <div class="cart-product-img">
                                        <img src="{{ order_item.item.photo_main.url }}" alt="product" />
                                    </div>
                                    <div class="cart-product-content">
                                        <div class="cart-product-name">
                                            <h6>{{ order_item.item.title }}</h6>
                                        </div>
                                    </div>
                                </td>
                                <td class="cart-product-price">{{ order_item.item.price|intcomma:False }} تومان</td>
                                <td class="cart-product-quantity">
                                    <div class="product-quantity">
                                        <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><input
                                                class="minus" type="button" value="-"></a>
                                        <input type="text" id="pro1-qunt" value="{{ order_item.quantity }}" class="qty"
                                            readonly="">
                                        <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><input class="plus"
                                                type="button" value="+"></a>
                                    </div>
                                </td>
                                <td class="cart-product-total">
                                    <span>{% if order_item.item.discount_price %}
                                        {{ order_item.get_total_discount_item_price|intcomma:False }} تومان
                                        <span class="badge badge-primary">ذخیره
                                            {{ order_item.get_amount_saved|intcomma:False }} تومان</span>
                                        {% else %}
                                        {{ order_item.get_total_item_price|intcomma:False }} تومان
                                        {% endif %}</span>
                                    <a href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                        <div class="cart-product-remove">x</div>
                                    </a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="5">سبد خرید شما خالی است .</td>
                            </tr>
                            <!-- .cart-product end -->
                            {% endfor %}

                            <!-- .cart-product end -->
                            <tr class="cart-product-action">
                                <td colspan="4">
                                    <div class="row clearfix">
                                        <div class="col-sm-12 col-md-12 col-lg-8">
                                            <form class="form-inline">
                                                <input type="text" class="form-control" id="coupon"
                                                    placeholder="کد تخفیف : ">
                                                <button type="submit" class="btn btn--secondary  btn--rounded">اعمال
                                                    تخفیف</button>
                                            </form>
                                        </div>
                                        <!-- .col-lg-6 end -->
                                        <div class="col-sm-12 col-md-12 col-lg-4 ">
                                            <a class="btn btn--secondary btn--bordered btn--rounded" href="/">به
                                                روزرسانی سبد</a>
                                        </div>
                                        <!-- .col-lg-6 end -->
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <!-- .cart-table end -->
                <div class="cart-product-action">
                    <div class="cart-copoun">
                        <!-- .col-lg-6 end -->
                        <h2>مجموع کل سبد خرید</h2>
                        <table id="price-total" cellspacing="0" class="shop_table shop_table_responsive table ns-table">

                            <tbody>
                                <tr class="sub--total">
                                    <th> قیمت کل </th>
                                    <td data-title=" قیمت کل "><span class="Price-amount amount"><span
                                                class="Price-currencySymbol"></span>&nbsp; {{ order.get_total|intcomma:False }}
                                            تومان</span>
                                    </td>
                                </tr>

                                <tr class="total">
                                    <th>حمل و نقل : </th>
                                    <td data-title="حمل ونقل : ">
                                        <span class="Price-amount amount">
                                            <label for="al"> حمل و نقل معمولی : </label>
                                            <span class="Price-currencySymbol"></span>&nbsp;</span>
                                        <p class="woocommerce-shipping-destination">
                                            گزینه های حمل و نقل در هنگام پرداخت به روز می شوند. </p>
                                    </td>
                                </tr>

                                <tr class="order-total">
                                    <th>مجموع</th>
                                    <td data-title="مجموع"><strong><span class="woocommerce-Price-amount amount"><span
                                                    class="woocommerce-Price-currencySymbol"></span>&nbsp;{{ order.get_total|intcomma:False }}
                                                تومان</span></strong>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                        <div class="proceed-to-checkout">
                            <a class="btn btn--primary btn--rounded " href="/checkout/">اقدام به پرداخت</a>
                        </div>
                        <!-- .checkout-panel end -->
                    </div>
                </div>

            </div>
            <!-- .col-lg-12 end -->
        </div>
        <!-- .row end -->
    </div>
    <!-- .container end -->
</section>
<!-- #shopcart end -->

{% endblock content %}